aws_region            = "us-east-2"
project_name          = "redroomsim"
azs                   = ["us-east-2a", "us-east-2b"]
vpc_cidr              = "10.0.0.0/16"
public_subnet_cidrs   = ["10.0.1.0/24", "10.0.2.0/24"]
private_subnet_cidrs  = ["10.0.101.0/24", "10.0.102.0/24"]
domain_name           = "redroomsim.com"
subdomain             = "app"
zone_comment          = "Primary domain for RedRoomSim"
rds_instance_class    = "db.t3.micro"
rds_db_name           = "redroomsimdb"
lambda_memory_size    = 512
lambda_timeout        = 30
frontend_bucket_name  = "redroomsim-frontend-bucket"
acm_validation_method = "DNS"
environment           = "development"
