name: Deploy Infrastructure and Frontend

on:
  push:
    branches: [main]

jobs:
  deploy:
    name: Deploy Infra + Frontend
    runs-on: ubuntu-latest

    env:
      AWS_REGION: us-east-1
      TF_VAR_RDS_USERNAME: ${{ secrets.TF_VAR_RDS_USERNAME }}
      TF_VAR_RDS_PASSWORD: ${{ secrets.TF_VAR_RDS_PASSWORD }}

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ env.AWS_REGION }}
      
      - name: Install zip
        run: sudo apt-get install -y zip

      - name: Zip FastAPI app
        run: |
          cd infra/fastapi-lambda/app
          zip -r aws_api_artifacts.zip . -x "*.git*" "*.venv*" "__pycache__/*" "*.pyc" "*.pyo"

      # ----------------------
      # Terraform Deployment
      # ----------------------
      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v3

      - name: Terraform Init
        working-directory: ./infra
        run: terraform init

      - name: Terraform Plan
        working-directory: ./infra
        run: terraform plan

      - name: Terraform Apply
        working-directory: ./infra
        run: terraform apply --auto-approve

      - name: Terraform Output
        id: tf_output
        working-directory: ./infra
        run: |
          terraform output -raw cloudfront_distribution_id > cloudfront_id.txt

      - name: Load CloudFront ID
        id: load_cf
        run: |
          echo "CLOUDFRONT_ID=$(cat ./infra/cloudfront_id.txt)" >> $GITHUB_ENV

      # ----------------------
      # React Frontend Build + Deploy
      # ----------------------
      - name: Install frontend dependencies
        working-directory: ./frontend
        run: npm install

      - name: Build React app
        working-directory: ./frontend
        run: npm run build
        env:
          VITE_FIREBASE_API_KEY: ${{ secrets.VITE_FIREBASE_API_KEY }}
          VITE_FIREBASE_AUTH_DOMAIN: ${{ secrets.VITE_FIREBASE_AUTH_DOMAIN }}
          VITE_FIREBASE_PROJECT_ID: ${{ secrets.VITE_FIREBASE_PROJECT_ID }}
          VITE_FIREBASE_STORAGE_BUCKET: ${{ secrets.VITE_FIREBASE_STORAGE_BUCKET }}
          VITE_FIREBASE_MESSAGING_SENDER_ID: ${{ secrets.VITE_FIREBASE_MESSAGING_SENDER_ID }}
          VITE_FIREBASE_APP_ID: ${{ secrets.VITE_FIREBASE_APP_ID }}

      - name: Deploy to S3
        run: |
          aws s3 sync ./frontend/dist s3://redroomsim-frontend-bucket --delete

      - name: Invalidate CloudFront cache
        run: |
          aws cloudfront create-invalidation \
            --distribution-id $CLOUDFRONT_ID \
            --paths "/*"
